server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: Order
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**, /menus/**, /orderStates/**
        - id: Pay
          uri: http://localhost:8082
          predicates:
            - Path=/pays/**, 
        - id: Order Management
          uri: http://localhost:8083
          predicates:
            - Path=/orderManagements/**, 
        - id: Kitchen
          uri: http://localhost:8084
          predicates:
            - Path=/cooks/**, 
        - id: Delivery
          uri: http://localhost:8085
          predicates:
            - Path=/deliveries/**, 
        - id: Customer Management
          uri: http://localhost:8086
          predicates:
            - Path=, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: Order
          uri: http://order:8080
          predicates:
            - Path=/orders/**, /menus/**, /orderStates/**
        - id: Pay
          uri: http://pay:8080
          predicates:
            - Path=/pays/**, 
        - id: Order Management
          uri: http://orderManagement:8080
          predicates:
            - Path=/orderManagements/**, 
        - id: Kitchen
          uri: http://kitchen:8080
          predicates:
            - Path=/cooks/**, 
        - id: Delivery
          uri: http://delivery:8080
          predicates:
            - Path=/deliveries/**, 
        - id: Customer Management
          uri: http://customerManagement:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
