apiVersion: apps/v1
kind: Deployment
metadata:
  name: Order Management
  labels:
    app: Order Management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Order Management
  template:
    metadata:
      labels:
        app: Order Management
    spec:
      containers:
        - name: Order Management
          image: username/Order Management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5